# Generated by Django 2.0.7 on 2018-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181216_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_abstract',
            field=models.CharField(default='zz', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_author',
            field=models.CharField(default='zzz', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercard',
            name='score',
            field=models.FloatField(default=None),
        ),
    ]
