# Generated by Django 2.0.7 on 2018-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20181216_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
