# Generated by Django 2.1.3 on 2018-12-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='quiz_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
